defaults: &defaults
  api:
    url: 'http://127.0.0.1:3000/api'

development:
  <<: *defaults

test:
  <<: *defaults
  student_api:
    url: 'http://api-rspec.example.com/api'

production:
  <<: *defaults